routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');


/****************Admin Routes Start ****************/
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function(){

    Route::get('/', function(){
        return view('admin.dashboard');
    })->name('admin');

    Route::resource('banner','BannerController')->except('show');
    Route::resource('category','CategoryController');
    Route::resource('products','ProductController');

    ROute::post('/category/child','CategoryController@getChildCats')->name('get-child');

    Route::get('file-manager', function(){
        return view('admin.file-manager');
    });

});
/****************Admin Routes End ****************/



/****************Vendor Routes Start ****************/
Route::group(['prefix' => 'vendor', 'middleware' => ['auth', 'vendor']], function(){

    Route::get('/', 'HomeController@vendor')->name('vendor');

});
/****************Vendor Routes End ****************/


/****************Customer Routes Start ****************/
Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'customer']], function(){

    Route::get('/', function(){
        return view('home');
    })->name('customer');

});
/****************Customer Routes End ****************/

resources/views/admin/banner-form.blade.php
@extends('admin.layouts.admin')
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Banner {{ isset($banner_data) ? 'Update' : 'Add' }}</div>
                    </div>
                    <div class="ibox-body">
                        @if(isset($banner_data))
                            {{Form::open(['url'=>route('banner.update', $banner_data->id), 'class'=>'form', 'id'=>'banner_add', 'files'=>true, 'method' => 'patch'])}}

                        @else

                            {{Form::open(['url'=>route('banner.store'), 'class'=>'form', 'id'=>'banner_add', 'files'=>true])}}
                        @endif

                        <div class="form-group row">
                            {{ Form::label('title','Title:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::text('title', @$banner_data->title, ['class'=>'form-control form-control-sm'.($errors->has('title') ? 'is-invalid' : ''), 'id'=>'title', 'required'=>true, ]) }}
                                @error('title')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('link','Link:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::url('link', @$banner_data->link, ['class'=>'form-control form-control-sm'.($errors->has('link') ? 'is-invalid' : ''), 'id'=>'link', 'required'=>true, ]) }}
                                @error('link')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('status','Status:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::select('status',['active'=>'Active','inactive'=>'Inactive'], @$banner_data->status,['class'=>'form-control form-control-sm'.($errors->has('status') ? 'is-invalid' : ''), 'id'=>'status', 'required'=>true, ]) }}

                                @error('status')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('image','Image:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-4">
                                {{ Form::file('image', ['class'=>'form-control-file'.($errors->has('image') ? 'is-invalid' : ''), 'id'=>'image', 'required'=>(isset($banner_data) ? false : true), 'accept'=>'image/*']) }}
                                @error('image')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                            <div class="col-sm-4">
                                @if(isset($banner_data) && $banner_data->image != null && file_exists(public_path().'/uploads/banner/Thumb-'.$banner_data->image))
                                    <img src="{{asset('/uploads/banner/Thumb-').$banner_data->image}}" alt="" class="img img-responsive img-thumbnail">
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('','', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::button('<i class="fa fa-trash"></i> Reset',['class'=>'btn btn-danger', 'type'=>'reset']) }}
                                {{ Form::button('<i class="fa fa-send"></i> Submit',['class'=>'btn btn-success', 'type'=>'submit']) }}
                            </div>
                        </div>
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/banner.blade.php
@extends('admin.layouts.admin')
@section('content')

  <div class="page-content fade-in-up">

    <div class="row">
      <div class="col-lg-12">
        <div class="ibox">
          <div class="ibox-head">
            <div class="ibox-title">Banner List</div>
            <div class="ibox-tools">
              <a href="{{route('banner.create')}}" class="btn btn-primary"><i class="fa fa-plus">Add New</i> </a>
            </div>
          </div>
          <div class="ibox-body">
            <table class="table table-striped table-hover">
              <thead>
              <tr>
                <th>Title</th>
                <th>Thumbnail</th>
                <th>Link</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
              </thead>
              <tbody>
              @if($banner_list)
                @foreach($banner_list as $key => $value)
                  <tr>
                    <td>{{$key + 1}}</td>
                    <td>
                      @if($value->image != null && file_exists(public_path().'/uploads/banner/Thumb-'.$value->image))
                        <img src="{{asset('/uploads/banner/Thumb-').$value->image}}" alt="" class="img img-responsive img-thumbnail">
                      @endif
                    </td>
                    <td>
                      <a href="{{$value->link}}" target="_banner">{{$value->link}}</a>
                    </td>
                    <td>{{$value->status}}</td>
                    <td>
                      <a href="{{route('banner.edit', $value->id)}}" class="btn btn-success" style="border-radius: 50%; margin-bottom: 2px">
                        <i class="fa fa-pencil"></i>
                      </a>

                      {{ Form::open(['url' => route('banner.destroy', $value->id), 'class' => 'form', 'method'=>'delete', 'onsubmit' => "return confirm('Are you sure you want to delete this banner?')"]) }}
                      {{ Form::button("<i class='fa fa-trash'></i>",['class' => 'btn btn-danger', 'style' => 'border-radius:50%', 'type' => 'submit']) }}
                      {{ Form::close() }}
                    </td>
                  </tr>
                @endforeach
              @endif
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>


  </div>
@endsection

resources/views/admin/category-form.blade.php
@extends('admin.layouts.admin')
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Category {{ isset($category_data) ? 'Update' : 'Add' }}</div>
                    </div>
                    <div class="ibox-body">
                        @if(isset($category_data))
                            {{Form::open(['url'=>route('category.update', $category_data->id), 'class'=>'form', 'id'=>'category_add', 'files'=>true, 'method' => 'patch'])}}

                        @else

                            {{Form::open(['url'=>route('category.store'), 'class'=>'form', 'id'=>'category_add', 'files'=>true])}}
                        @endif

                        <div class="form-group row">
                            {{ Form::label('title','Title:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::text('title', @$category_data->title, ['class'=>'form-control form-control-sm'.($errors->has('title') ? 'is-invalid' : ''), 'id'=>'title', 'required'=>true, ]) }}
                                @error('title')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('summary','Summary:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::textarea('summary', @$category_data->summary, ['class'=>'form-control form-control-sm'.($errors->has('summary') ? 'is-invalid' : ''), 'id'=>'summary', 'required'=>false, 'placeholder' =>'Enter the summary', 'rows' => 5, 'style' => 'resize:none']) }}
                                @error('summary')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('is_parent','Is Parent:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-1">
                                {{ Form::checkbox('is_parent', 1, @$category_data->is_parent, ['class'=>'form-control form-control-sm'.($errors->has('summary') ? 'is-invalid' : ''), 'id'=>'is_parent']) }}
                                @error('summary')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row {{@$category_data->is_parent ? 'd-none' : ''}}" id="parent_id_div">
                            {{ Form::label('parent_id','Parent Category:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::select('parent_id', $parent_cats, @$category_data->parent_id, ['class'=>'form-control form-control-sm'.($errors->has('status') ? 'is-invalid' : ''), 'id'=>'parent_id', 'required'=>false ]) }}

                                @error('parent_id')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('status','Status:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::select('status',['active'=>'Active','inactive'=>'Inactive'], @$category_data->status,['class'=>'form-control form-control-sm'.($errors->has('status') ? 'is-invalid' : ''), 'id'=>'status', 'required'=>true, ]) }}

                                @error('status')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('image','Image:', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-4">
                                {{ Form::file('image', ['class'=>'form-control-file'.($errors->has('image') ? 'is-invalid' : ''), 'id'=>'image', 'required'=>(isset($category_data) ? false : true), 'accept'=>'image/*']) }}
                                @error('image')
                                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                                @enderror
                            </div>
                            <div class="col-sm-4">
                                @if(isset($category_data) && $category_data->image != null && file_exists(public_path().'/uploads/category/Thumb-'.$category_data->image))
                                    <img src="{{asset('/uploads/category/Thumb-').$category_data->image}}" alt="" class="img img-responsive img-thumbnail">
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ Form::label('','', ['class'=>'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::button('<i class="fa fa-trash"></i> Reset',['class'=>'btn btn-danger', 'type'=>'reset']) }}
                                {{ Form::button('<i class="fa fa-send"></i> Submit',['class'=>'btn btn-success', 'type'=>'submit']) }}
                            </div>
                        </div>
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

    <script>
        $('#is_parent').change(function () {
            var is_checked = $('#is_parent').prop('checked');
            if (is_checked){
                $('#parent_id_div').addClass('d-none');

            } else {
                $('#parent_id_div').removeClass('d-none');
            }
        })
    </script>
    @endsection

resources/views/admin/category.blade.php
@extends('admin.layouts.admin')
@section('content')

  <div class="page-content fade-in-up">

    <div class="row">
      <div class="col-lg-12">
        <div class="ibox">
          <div class="ibox-head">
            <div class="ibox-title">Category List</div>
            <div class="ibox-tools">
              <a href="{{route('category.create')}}" class="btn btn-primary"><i class="fa fa-plus">Add New</i> </a>
            </div>
          </div>
          <div class="ibox-body">
            <table class="table table-striped table-hover">
              <thead>
              <tr>
                <th>S.N</th>
                <th>Title</th>
                <th>Thumbnail</th>
                <th>Slug</th>
                <th>Summary</th>
                <th>Is Parent?</th>
                <th>Parent</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
              </thead>
              <tbody>
              @if($category_list)
                @foreach($category_list as $key => $value)
                  <tr>
                    <td>{{$key + 1}}</td>
                    <td>{{$value->title}}</td>
                    <td>
                      @if($value->image != null && file_exists(public_path().'/uploads/category/Thumb-'.$value->image))
                        <img src="{{asset('/uploads/category/Thumb-').$value->image}}" alt="" class="img img-responsive img-thumbnail">
                      @endif
                    </td>
                    <td>{{$value->slug}}</td>
                    <td>
                      <a href="{{$value->summary}}" target="_category">{{$value->summary}}</a>
                    </td>
                    <td>{{$value->is_parent == 1 ? "Yes" : "No"}}</td>
                    <td>{{$value->parent_id == 0 ? "N/a" : $value->parent_info['title']}}</td>
                    <td>{{$value->status}}</td>
                    <td>
                      <a href="{{route('category.edit', $value->id)}}" class="btn btn-success" style="border-radius: 50%; margin-bottom: 2px"><i class="fa fa-pencil"></i>
                      </a>

                      {{ Form::open(['url' => route('category.destroy', $value->id), 'class' => 'form', 'method'=>'delete', 'onsubmit' => "return confirm('Are you sure you want to delete this category?')"]) }}
                      {{ Form::button("<i class='fa fa-trash'></i>",['class' => 'btn btn-danger', 'style' => 'border-radius:50%', 'type' => 'submit']) }}
                      {{ Form::close() }}
                    </td>
                  </tr>
                @endforeach
              @endif
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>


  </div>
@endsection

resources/views/admin/file-manager.blade.php
@extends('admin.layouts.admin')
@section('content')
  <div class="page-content fade-in-up">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox">
          <div class="ibox-head">
            <div class="ibox-title">Media Manager</div>
          </div>
          <div class="ibox-body">
            <div class="input-group">
                 <span class="input-group-btn">
                   <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                     <i class="fa fa-picture-o"></i> Choose
                   </a>
                 </span>
              <input id="thumbnail" class="form-control" type="text" name="filepath">
            </div>
            <div class="row">
              <div id="holder" style="margin-top:15px;max-height:100px;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    @endsection

    @section('scripts')
      <script src={{asset('vendor/laravel-filemanager/js/lfm.js')}}></script>
      <script>$('#lfm').filemanager('image');</script>
@endsection

resources/views/admin/product-form.blade.php
@extends('admin.layouts.admin')

@section('styles')
  <link rel="stylesheet" href="{{asset('assets/admin/css/select2.css')}}">
  <link rel="stylesheet" href="{{asset('assets/admin/css/select2.css')}}">
@endsection

@section('content')
  <div class="page-content fade-in-up">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox">
          <div class="ibox-head">
            <div class="ibox-title">Product {{ isset($product_data) ? 'Update' : 'Add' }}</div>
          </div>
          <div class="ibox-body">
            @if(isset($product_data))
              {{Form::open(['url'=>route('product.update', $product_data->id), 'class'=>'form', 'id'=>'product_add', 'files'=>true, 'method' => 'patch'])}}

            @else

              {{Form::open(['url'=>route('products.store'), 'class'=>'form', 'id'=>'product_add', 'files'=>true])}}
            @endif

            <div class="form-group row">
              {{ Form::label('title','Title:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::text('title', @$product_data->title, ['class'=>'form-control form-control-sm'.($errors->has('title') ? 'is-invalid' : ''), 'id'=>'title', 'required'=>true, ]) }}
                @error('title')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              {{ Form::label('summary','Summary:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::textarea('summary', @$product_data->summary, ['class'=>'form-control form-control-sm'.($errors->has('summary') ? 'is-invalid' : ''), 'id'=>'summary', 'required'=>false, 'placeholder' =>'Enter the summary', 'rows' => 5, 'style' => 'resize:none']) }}
                @error('summary')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              {{ Form::label('description','Description:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::textarea('description', @$product_data->description, ['class'=>'form-control form-control-sm'.($errors->has('description') ? 'is-invalid' : ''), 'id'=>'description', 'placeholder' =>'Enter the description', 'rows' => 5, 'style' => 'resize:none']) }}
                @error('description')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              {{ Form::label('cat_id','Category:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::select('cat_id', $parent_cats, @$product_data->cat_id, ['class'=>'form-control form-control-sm category_select_2'.($errors->has('cat_id') ? 'is-invalid' : ''), 'id'=>'cat_id','placeholder'=>'Select One Category']) }}
                @error('cat_id')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
            </div>

            <div class="form-group row d-none" id="child_cat_div">
              {{ Form::label('sub_cat_id','Sub-category:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::select('sub_cat_id', [], @$product_data->sub_cat_id, ['class'=>'form-control form-control-sm '.($errors->has('sub_cat_id') ? 'is-invalid' : ''), 'id'=>'sub_cat_id']) }}
                @error('sub_cat_id')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
            </div>

              <div class="form-group row">
                {{ Form::label('price','Price (Rs):', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                  {{ Form::number('price', @$product_data->price, ['class'=>'form-control form-control-sm'.($errors->has('price') ? 'is-invalid' : ''), 'id'=>'price', 'required'=>true, 'placeholder' => "Enter price",'min'=>"10" ]) }}
                  @error('price')
                  <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                {{ Form::label('discount','Discount (%):', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                  {{ Form::number('discount', @$product_data->discount, ['class'=>'form-control form-control-sm'.($errors->has('discount') ? 'is-invalid' : ''), 'id'=>'discount', 'required'=>false, 'placeholder' => "Enter discount",'min'=>"0", 'max'=>'95' ]) }}
                  @error('discount')
                  <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                {{ Form::label('stock','Stock:', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                  {{ Form::number('stock', @$product_data->stock, ['class'=>'form-control form-control-sm'.($errors->has('stock') ? 'is-invalid' : ''), 'id'=>'stock', 'required'=>false, 'placeholder' => "Enter stock",'min'=>"0" ]) }}
                  @error('stock')
                  <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                {{ Form::label('brand','Brand:', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                  {{ Form::text('brand', @$product_data->brand, ['class'=>'form-control form-control-sm'.($errors->has('brand') ? 'is-invalid' : ''), 'id'=>'brand', 'required'=>false, 'placeholder' => "Enter brand" ]) }}
                  @error('brand')
                  <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                {{ Form::label('is_featured','Featured Product:', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                  {{ Form::checkbox('is_featured', 1, @$product_data->is_featured, ['class'=>''.($errors->has('is_featured') ? 'is-invalid' : ''), 'id'=>'is_featured' ]) }} Yes
                  @error('is_featured')
                  <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                  @enderror
                </div>
              </div>

              <div class="form-group row">
                {{ Form::label('vendor_id','Vendor:', ['class'=>'col-sm-3']) }}
                <div class="col-sm-9">
                  {{ Form::select('vendor_id', $vendors, @$product_data->vendor_id, ['class'=>'form-control form-control-sm category_select_2 '.($errors->has('vendor_id') ? 'is-invalid' : ''), 'id'=>'vendor_id','placeholder'=>'Select One Vendor']) }}
                  @error('vendor_id')
                  <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                  @enderror
                </div>
              </div>


              <div class="form-group row">
              {{ Form::label('status','Status:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::select('status',['active'=>'Active','inactive'=>'Inactive'], @$product_data->status,['class'=>'form-control form-control-sm'.($errors->has('status') ? 'is-invalid' : ''), 'id'=>'status', 'required'=>true, ]) }}

                @error('status')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              {{ Form::label('image','Image:', ['class'=>'col-sm-3']) }}
              <div class="col-sm-4">
                {{ Form::file('image', ['class'=>'form-control-file'.($errors->has('image') ? 'is-invalid' : ''), 'id'=>'image', 'required'=>(isset($product_data) ? false : true), 'accept'=>'image/*']) }}
                @error('image')
                <span class="invalid-feedback">
                                    {{$message}}
                                </span>
                @enderror
              </div>
              <div class="col-sm-4">
                @if(isset($product_data) && $product_data->image != null && file_exists(public_path().'/uploads/product/Thumb-'.$product_data->image))
                  <img src="{{asset('/uploads/product/Thumb-').$product_data->image}}" alt="" class="img img-responsive img-thumbnail">
                @endif
              </div>
            </div>

            <div class="form-group row">
              {{ Form::label('','', ['class'=>'col-sm-3']) }}
              <div class="col-sm-9">
                {{ Form::button('<i class="fa fa-trash"></i> Reset',['class'=>'btn btn-danger', 'type'=>'reset']) }}
                {{ Form::button('<i class="fa fa-send"></i> Submit',['class'=>'btn btn-success', 'type'=>'submit']) }}
              </div>
            </div>
            {{Form::close()}}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('scripts')
  <script src="{{asset('assets/admin/js/select2.min.js')}}"></script>
  <script>
      $(document).ready(function() {
          $('#cat_id').select2();
          $('#sub_cat_id').select2({width: "100%"});
      });
  </script>
  <script>
      $('#is_parent').change(function (e) {
          var is_checked = $('#is_parent').prop('checked');
          if (is_checked){
              $('#parent_id_div').addClass('d-none');

          } else {
              $('#parent_id_div').removeClass('d-none');
          }
      });

      $('#cat_id').change(function (e) {
          var cat_id = $(this).val();
          //ajax
          $.ajax({
              url: "{{route('get-child')}}",
              type: "post",
              data: {
                  _token: "{{csrf_token()}}",
                  cat_id: cat_id
              },
              success: function (response) {
                  if(typeof (response) != 'object'){
                      response = $.parseJSON(response);
                  }
                  var html_option = '<option value="" selected>Select Any One</option>';
                  if(response.status){
                      $('#child_cat_div').removeClass('d-none');

                      $.each(response.data, function (key, value) {
                          html_option += "<option value='" +key+"'>"+value+"</option>";
                      });
                  }else{
                      $('#child_cat_div').addClass('d-none')
                  }
                  $('#sub_cat_id').html(html_option);
              }

          });
      });
  </script>
@endsection