routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');


/****************Admin Routes Start ****************/
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function(){

    Route::get('/', function(){
        return view('admin.dashboard');
    })->name('admin');

    Route::resource('banner','BannerController')->except('show');
    Route::resource('category','CategoryController');
    Route::resource('products','ProductController');

    ROute::post('/category/child','CategoryController@getChildCats')->name('get-child');

    Route::get('file-manager', function(){
        return view('admin.file-manager');
    });

});
/****************Admin Routes End ****************/



/****************Vendor Routes Start ****************/
Route::group(['prefix' => 'vendor', 'middleware' => ['auth', 'vendor']], function(){

    Route::get('/', 'HomeController@vendor')->name('vendor');

});
/****************Vendor Routes End ****************/


/****************Customer Routes Start ****************/
Route::group(['prefix' => 'customer', 'middleware' => ['auth', 'customer']], function(){

    Route::get('/', function(){
        return view('home');
    })->name('customer');

});
/****************Customer Routes End ****************/

resources/views/admin/partials/notifications.blade.php
@if(session('success'))
    <div class="alert alert-success alert-bordered">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger alert-bordered">
        {{session('error')}}
    </div>
@endif

@if(session('warning'))
    <div class="alert alert-warning alert-bordered">
        {{session('warning')}}
    </div>
@endif

resources/views/admin/partials/sidebar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
  <div id="sidebar-collapse">
    <div class="admin-block d-flex">
      <div>
        <img src="{{ asset('assets/admin/img/admin-avatar.png') }}" width="45px" />
      </div>
      <div class="admin-info">
        <div class="font-strong">James Brown</div><small>Administrator</small></div>
    </div>
    <ul class="side-menu metismenu">
      <li>
        <a class="active" href="index.html"><i class="sidebar-item-icon fa fa-th-large"></i>
          <span class="nav-label">Dashboard</span>
        </a>
      </li>

      <li class="heading">FEATURES</li>

      <li>
        <a href="{{route('banner.index')}}"><i class="sidebar-item-icon fa fa-image"></i>
          <span class="nav-label">Banner Management</span>
        </a>
      </li>
      <li>
        <a href="{{route('category.index')}}"><i class="sidebar-item-icon fa fa-sitemap"></i>
          <span class="nav-label">Category Management</span>
        </a>
      </li>
      <li>
        <a href="icons.html"><i class="sidebar-item-icon fa fa-image"></i>
          <span class="nav-label">Media Management</span>
        </a>
      </li>
      <li>
        <a href="{{ route('products.index') }}"><i class="sidebar-item-icon fa fa-shopping-basket"></i>
          <span class="nav-label">Product Management</span>
        </a>
      </li>
      <li>
        <a href="icons.html"><i class="sidebar-item-icon fa fa-shopping-cart"></i>
          <span class="nav-label">Order Management</span>
        </a>
      </li>
      <li>
        <a href="icons.html"><i class="sidebar-item-icon fa fa-users"></i>
          <span class="nav-label">Users Management</span>
        </a>
      </li>
      <li>
        <a href="icons.html"><i class="sidebar-item-icon fa fa-dollar"></i>
          <span class="nav-label">Ads Management</span>
        </a>
      </li>
      <li>
        <a href="icons.html"><i class="sidebar-item-icon fa fa-file"></i>
          <span class="nav-label">Pages Management</span>
        </a>
      </li>
      <li>
        <a href="icons.html"><i class="sidebar-item-icon fa fa-comments"></i>
          <span class="nav-label">Review Management</span>
        </a>
      </li>
    </ul>
  </div>
</nav>
<!-- END SIDEBAR-->

resources/views/admin/partials/top-nav.blade.php
<!-- START HEADER-->
<header class="header">
  <div class="page-brand">
    <a class="link" href="{{route('admin')}}">
                    <span class="brand">Admin
                        <span class="brand-tip">CAST</span>
                    </span>
      <span class="brand-mini">AC</span>
    </a>
  </div>
  <div class="flexbox flex-1">
    <!-- START TOP-LEFT TOOLBAR-->
    <ul class="nav navbar-toolbar">
      <li>
        <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
      </li>

    </ul>
    <!-- END TOP-LEFT TOOLBAR-->
    <!-- START TOP-RIGHT TOOLBAR-->
    <ul class="nav navbar-toolbar">
      <li class="dropdown dropdown-notification">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell-o rel"><span class="notify-signal"></span></i></a>
        <ul class="dropdown-menu dropdown-menu-right dropdown-menu-media">
          <li class="dropdown-menu-header">
            <div>
              <span><strong>5 New</strong> Notifications</span>
              <a class="pull-right" href="javascript:;">view all</a>
            </div>
          </li>
          <li class="list-group list-group-divider scroller" data-height="240px" data-color="#71808f">
            <div>
              <a class="list-group-item">
                <div class="media">
                  <div class="media-img">
                    <span class="badge badge-success badge-big"><i class="fa fa-check"></i></span>
                  </div>
                  <div class="media-body">
                    <div class="font-13">4 task compiled</div><small class="text-muted">22 mins</small></div>
                </div>
              </a>
              <a class="list-group-item">
                <div class="media">
                  <div class="media-img">
                    <span class="badge badge-default badge-big"><i class="fa fa-shopping-basket"></i></span>
                  </div>
                  <div class="media-body">
                    <div class="font-13">You have 12 new orders</div><small class="text-muted">40 mins</small></div>
                </div>
              </a>
              <a class="list-group-item">
                <div class="media">
                  <div class="media-img">
                    <span class="badge badge-danger badge-big"><i class="fa fa-bolt"></i></span>
                  </div>
                  <div class="media-body">
                    <div class="font-13">Server #7 rebooted</div><small class="text-muted">2 hrs</small></div>
                </div>
              </a>
              <a class="list-group-item">
                <div class="media">
                  <div class="media-img">
                    <span class="badge badge-success badge-big"><i class="fa fa-user"></i></span>
                  </div>
                  <div class="media-body">
                    <div class="font-13">New user registered</div><small class="text-muted">2 hrs</small></div>
                </div>
              </a>
            </div>
          </li>
        </ul>
      </li>

      <li class="dropdown dropdown-user">
        <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
          <img src="{{ asset('assets/admin/img/admin-avatar.png') }}" />
          <span></span>Admin<i class="fa fa-angle-down m-l-5"></i></a>
        <ul class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{{ route('logout') }}"
             onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
            <i class="fa fa-power-off"></i> Logout
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
        </ul>
      </li>
    </ul>
    <!-- END TOP-RIGHT TOOLBAR-->
  </div>
</header>
<!-- END HEADER-->